/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_selenium_automation_tasks;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
